[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.engagements.email"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["engagements", "email", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.engagements.email"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
